version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/dagger"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/examples/middleware"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/tutorial/whatsup"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /.bingo
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /tutorials/whatsup
    schedule:
      interval: daily
